version: "3.9"

services:
  tools-frontend:
    container_name: tools-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    image: ${CR_HOST}/${CR_REGISTRY}/${CR_IMAGE}:latest
    environment:
      VITE_API_URL: ${VITE_API_URL}
    networks:
      - internet
    ports:
      - 3405:80
    restart: unless-stopped

networks:
  # internal-network:
  #   driver: bridge
  #   internal: true
  internet:
    driver: bridge
